Feature/first practice
kio-55/effective-web-course pull request #1
Opened 2022-11-05 17:54 UTC by kio-55

Григорьев Кирилл

2022-11-06 17:36 UTC, annamyamikova requested changes
👍 за бота и README

На что обратить внимание:
- Основную ветку лучше называть не main, а master;
- PR должен называться как в примере: [LAB-1] Add markup, имя и фамилия должны быть быть в описании к PR;
- Я словила баг при резком изменении ширины, мобильное меню лагает
- Адаптивность не реализована для блока с сеткой, текст и блоки также скрываются за пределами экрана

Доп. задания не выполнены. Могу поставить 10 баллов, либо можешь доработать

2022-11-06 17:36 UTC, annamyamikova commented on first_practice/index.html
> +          class="example__item example__item_10 example__item_base example__item_pink"
Почему где-то используется дефис, а где-то нижнее подчеркивание?

2022-11-06 17:36 UTC, annamyamikova commented on first_practice/styles/reset.css
> +	border: none;
Советую использовать prettier

2022-11-06 17:36 UTC, annamyamikova commented on first_practice/styles/reset.css
> +	/*outline: none;*/
Не должно быть мертвого кода

2022-11-06 17:36 UTC, annamyamikova commented on first_practice/styles/styles.css
> +  color: #ffffff;
Если используешь переменные, то все цвета, шрифты, размер шрифтов должны быть  в переменных

2022-11-06 17:47 UTC, kio-55 commented on first_practice/index.html
> +          class="example__item example__item_10 example__item_base example__item_pink"
Дефис я использую для разделения нескольких слов в названии элемента, нижнее подчеркивание - это модификатор этого элемента.

2022-11-06 17:52 UTC, kio-55 commented on first_practice/styles/reset.css
> +	/*outline: none;*/
Спасибо! Я особо не обращал внимания на документ с обнулением стилей. Исправлю!

2022-11-06 17:52 UTC, kio-55 commented on first_practice/styles/styles.css
> +  color: #ffffff;
Спасибо! Исправлю

2022-11-11 15:09 UTC, annamyamikova approved these changes
<img width="209" alt="Screenshot 2022-11-11 at 21 08 23" src="https://user-images.githubusercontent.com/37665408/201368173-0cb87232-c218-417a-b33a-bad88a37d2ae.png">
На мобильной версии у текста нет отступа, сливается с блоком

<img width="208" alt="Screenshot 2022-11-11 at 21 09 10" src="https://user-images.githubusercontent.com/37665408/201368329-4b5500fa-fff8-4e22-8c47-11b9fa8fea17.png">
Инпуты можно растянуть по всей ширине

2022-11-11 15:09 UTC, annamyamikova commented on first_practice/fonts/inter.css
> +    font-weight: 400;
Если на проекте два отступа, то он должен быть во всех файлах

2022-11-11 15:09 UTC, annamyamikova commented on first_practice/index.html
> +                >
Очень странный перенос

2022-11-11 15:09 UTC, annamyamikova commented on first_practice/styles/adaptive.css
> +    background-color: #fff;
Цвета можно тоже выносить в переменные

2022-11-11 15:09 UTC, annamyamikova commented on first_practice/styles/styles.css
> +@import url(../fonts/inter.css);
лучше использовать абсолютные пути

2022-11-11 15:09 UTC, merged